apiVersion: v1
kind: Pod
metadata:
  name: todoapp-pod
  namespace: todoapp
spec:
  containers:
  - name: todoapp
    image: nizartem/todoapp:3.0.0
    ports:
    - containerPort: 8000
    readinessProbe:
      httpGet:
        path: /readiness/
        port: 8000
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /health/
        port: 8000
      initialDelaySeconds: 10
      periodSeconds: 20
  restartPolicy: Always
